concept(absorption_0, process, 'process of absorbing something').
concept(alphacell_0,  cell, 'one type of cell in the pancreas').
concept(betacell_0,         cell).
concept(blood_0,            body_fluid).
concept(carbohydrate,     body_fluid).
concept(catabolism,       process).
concept(cell_0,             cell).
concept(circulation,      material).
concept(concentration,    quantity).
concept(conversion,	      transformation).
concept(cue,              information).
concept(effect,           process).
concept(excretion,        creation).
concept(fat,              body_fluid).
concept(fluid,            body_fluid).
concept(glucagon,         body_fluid).
concept(gluconeogenesis,  creation).
concept(glucose,	      body_fluid).
concept(glycogen,	      body_fluid).
concept(glycogenesis,     creation).
concept(glycogenolysis,   creation).
concept(hormone,          protein).
concept(impact,           enhancement).
concept(insulin,          protein).
concept(islet,            body_part).
concept(keeping,          process).
concept(limit,	      quantity).
concept(lipogenesis,      creation).
concept(liver,            organ).
concept(manner,	      quality).
concept(mechanism,        process).
concept(metabolism,       process).
concept(molecule,         mass).
concept(muscle,           body_part).
concept(pancreas,         organ).
concept(peptide,          protein).
concept(plasma,	      material).
concept(promotion,        enhancement).
concept(production,       creation).
concept(protein,          protein).
concept(regulation,       enhancement).
concept(release,          process).
concept(secretion,	      creation).
concept(stimulation,      enhancement).
concept(stop,             enhancement).
concept(synthesis,        creation).
concept(taking,           process).
concept(tissue,           body_part).
concept(triglyceride,     body_fluid).

